export const FONTS = [
  "Roboto Slab",
  "Merriweather",
  "Playfair Display",
  "Lora",
  "PT Serif",
  "Noto Serif",
  "Libre Baskerville",
  "Old Standard TT",
  "Vollkorn",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",

  "Fira Sans",
  "Roboto Condensed",
  "Proza Libre",
  "Work Sans",
  "Oswald",
  "Bebas Neue",
  "Lobster",
  "Comfortaa",
  "Abril Fatface",
  "Alfa Slab One",
  "Cormorant",
  "Raleway",
  "Italiana",
  "Antic Didone",
  "Cinzel",
  "Dancing Script",
  "Pacifico",
  "Shadows Into Light",
  "Indie Flower",
  "Caveat",
  "Homemade Apple",
  "League Script",
  "Cedarville Cursive",
  "Berkshire Swash",
  "La Belle Aurore",
  "Roboto Mono",
  "Inconsolata",
  "Source Code Pro",
  "IBM Plex Mono",
  "Space Mono",
  "Noto Sans",
  "Anonymous Pro",
  "Azeret Mono",
  "JetBrains Mono",
  "Courier Prime",
];
